In [20]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4

cpu


In [2]:
with open('wizard_of_oz.txt','r',encoding='utf-8') as f:
    text = f.read()

print(len(text))


232315


In [3]:
print(text[:200])



DOROTHY AND THE WIZARD IN OZ

  BY

  L. FRANK BAUM

  AUTHOR OF THE WIZARD OF OZ, THE LAND OF OZ, OZMA OF OZ, ETC.

  ILLUSTRATED BY JOHN R. NEILL

  BOOKS OF WONDER WILLIAM MORROW & CO., INC. NEW


In [7]:
chars = sorted(set(text))
print(chars)
len(chars)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


81

Tokenization

In [8]:
string_to_int = {ch:i for i,ch in enumerate(chars)} 
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[ch] for ch in s]
decode = lambda x: ''.join([int_to_string[i] for i in x])       

In [9]:
print(encode('hello'))  

[61, 58, 65, 65, 68]


In [10]:
decode(encode('hello')) 

'hello'

In [13]:
data = torch.tensor(encode(text),dtype=torch.long)  
data[:100]

tensor([80,  0,  0, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])

train-val split

In [14]:
n = 0.8
train_data = data[:int(n*len(data))]    
val_data = data[int(n*len(data)):]  

In [ ]:
# block_size = 8
x = train_data[:block_size]
y = train_data[1:block_size+1]  

for t in range(block_size):
    context = x[:t+1]
    target = y[t]   
    print(context, target)  

tensor([80]) tensor(0)
tensor([80,  0]) tensor(0)
tensor([80,  0,  0]) tensor(28)
tensor([80,  0,  0, 28]) tensor(39)
tensor([80,  0,  0, 28, 39]) tensor(42)
tensor([80,  0,  0, 28, 39, 42]) tensor(39)
tensor([80,  0,  0, 28, 39, 42, 39]) tensor(44)
tensor([80,  0,  0, 28, 39, 42, 39, 44]) tensor(32)
