In [1]:
import torch

In [9]:
nums = torch.randint(-100,100,(20,))
print(nums)

tensor([ 96,  33, -88,  44, -80,  -9, -73,  13, -99,  49,  72, -25, -95,  42,
         85, -11, -49, -79, -79,  54])


In [3]:
tensor = torch.tensor([(0.1,0.2),(1.4,2.5),(3.6,4.7)])
tensor

tensor([[0.1000, 0.2000],
        [1.4000, 2.5000],
        [3.6000, 4.7000]])

In [4]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
input = torch.empty((2,3))    
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
arange = torch.arange(8) 
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
linespace = torch.linspace(0,10,5)  
linespace

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [20]:
logspace = torch.logspace(-10,10,5)   
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [22]:
eye = torch.eye(6)
eye

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [24]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[72057594037927937,   281474976710656,     1099511627776],
        [       4294967296,          16777216,                 0]])

In [31]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities,10,replacement=True)
samples

tensor([1, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [36]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor,torch.tensor([6])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

In [39]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [40]:
out = torch.triu(torch.ones(5,5))   
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [46]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) ==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [47]:
out = torch.exp(out)
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [50]:
out = torch.zeros((2,3,4))
out = out.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [51]:
tensor1 = torch.tensor([1,2,3,4,5])
tensor2 = torch.tensor([6,7,8,9,10])
tensor3 = torch.tensor([11,12,13,14,15])

out = torch.stack((tensor1,tensor2,tensor3),dim=0)
out

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [55]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,4,bias=False)  
print(linear(sample))   

tensor([ 9.0512,  0.1906, -5.1291,  4.1881], grad_fn=<SqueezeBackward4>)


In [63]:
import torch.nn.functional as F
sample = torch.tensor([1.,2.,3.])
softmax_out = F.softmax(sample,dim=0)
print(softmax_out)

tensor([0.0900, 0.2447, 0.6652])
