In [1]:
import torch

In [9]:
nums = torch.randint(-100,100,(20,))
print(nums)

tensor([ 96,  33, -88,  44, -80,  -9, -73,  13, -99,  49,  72, -25, -95,  42,
         85, -11, -49, -79, -79,  54])


In [3]:
tensor = torch.tensor([(0.1,0.2),(1.4,2.5),(3.6,4.7)])
tensor

tensor([[0.1000, 0.2000],
        [1.4000, 2.5000],
        [3.6000, 4.7000]])

In [4]:
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
input = torch.empty((2,3))    
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
arange = torch.arange(8) 
arange

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
linespace = torch.linspace(0,10,5)  
linespace

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [20]:
logspace = torch.logspace(-10,10,5)   
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [22]:
eye = torch.eye(6)
eye

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [24]:
a = torch.empty((2,3),dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[72057594037927937,   281474976710656,     1099511627776],
        [       4294967296,          16777216,                 0]])

In [31]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities,10,replacement=True)
samples

tensor([1, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [36]:
tensor = torch.tensor([1,2,3,4,5])
out = torch.cat((tensor,torch.tensor([6])), dim=0)
out

tensor([1, 2, 3, 4, 5, 6])

In [39]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [40]:
out = torch.triu(torch.ones(5,5))   
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [46]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) ==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [47]:
out = torch.exp(out)
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [50]:
out = torch.zeros((2,3,4))
out = out.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [51]:
tensor1 = torch.tensor([1,2,3,4,5])
tensor2 = torch.tensor([6,7,8,9,10])
tensor3 = torch.tensor([11,12,13,14,15])

out = torch.stack((tensor1,tensor2,tensor3),dim=0)
out

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [55]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,4,bias=False)  
print(linear(sample))   

tensor([ 9.0512,  0.1906, -5.1291,  4.1881], grad_fn=<SqueezeBackward4>)


In [63]:
import torch.nn.functional as F
sample = torch.tensor([1.,2.,3.])
softmax_out = F.softmax(sample,dim=0)
print(softmax_out)

tensor([0.0900, 0.2447, 0.6652])


In [66]:
volab_size = 80
embedding_dim = 3   
embedding = nn.Embedding(volab_size, embedding_dim) 

# Example input: indices representing words
input_indices = torch.tensor([0, 1, 3])

# Get embeddings for input indices
output = embedding(input_indices)

print("Embedding Matrix:\n", embedding.weight)
print("Output Embeddings:\n", output)


Embedding Matrix:
 Parameter containing:
tensor([[-8.6742e-01, -1.8906e+00,  8.0141e-01],
        [ 1.9014e+00,  1.5473e+00, -1.0890e+00],
        [ 2.8760e-01,  5.4438e-01, -6.7637e-01],
        [-1.0395e+00, -8.0557e-01, -1.3654e-01],
        [ 1.4762e+00,  3.9589e-01, -4.5874e-01],
        [-1.8376e+00, -7.8064e-02,  7.1239e-01],
        [-1.5295e+00, -1.0686e+00, -1.4382e+00],
        [-9.3571e-01,  1.8644e+00,  6.7123e-01],
        [-3.3931e-01,  1.3566e-01, -7.4251e-01],
        [ 5.1094e-01,  7.1178e-01,  1.2774e-01],
        [-4.7085e-01, -2.6677e-01, -7.3531e-02],
        [-6.2621e-01, -1.1094e-01,  8.1324e-01],
        [-2.1885e+00, -1.5898e+00, -7.4725e-01],
        [-1.0949e+00,  1.1330e+00,  1.3515e+00],
        [-5.3057e-01,  1.2245e+00,  4.7059e-01],
        [-4.9762e-01,  1.1860e+00,  1.1245e+00],
        [ 1.0833e+00, -1.7950e+00,  3.0690e+00],
        [ 2.1134e+00,  4.6280e-01, -1.0402e+00],
        [ 1.6639e-01,  9.5676e-01, -8.3726e-01],
        [-3.1988e+00, -1.060

In [73]:
a = torch.tensor([(1,2),(3,4),(5,6)])   
b = torch.tensor([(1,2,3),(4,5,6)]) 
out = a@b
print(out)
print(torch.matmul(a,b))


tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])
tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])


In [78]:
int_64 = torch.randint(0,100,(3,2)).float()
float_32 = torch.rand((2,3))    
print(int_64)
print(float_32) 
print(int_64@float_32)  

tensor([[52., 53.],
        [15., 13.],
        [ 7., 17.]])
tensor([[0.8747, 0.4602, 0.1764],
        [0.0186, 0.0495, 0.3598]])
tensor([[46.4718, 26.5547, 28.2383],
        [13.3628,  7.5468,  7.3224],
        [ 6.4391,  4.0627,  7.3506]])
